name: "Build JAR"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: vars
        run: echo "::set-output name=short_sha::$(git rev-parse --short HEAD)"
      - name: Setup Java JDK
        uses: actions/setup-java@v2.0.0
        with:
          distribution: 'adopt'
          java-version: '8'
      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v1.0.1
      - name: Mount bazel cache  # Optional
        uses: actions/cache@v1
        with:
          path: "~/.cache/bazel"
          key: bazel
      - name: Test Copybara
        run: bazel test //...
      - name: Build Copybara
        run: bazel build //java/com/google/copybara:copybara_deploy.jar
      - name: Store built JAR
        uses: actions/upload-artifact@v2
        with:
          name: copybara.jar
          path: bazel-bin/java/com/google/copybara/copybara_deploy.jar
          if-no-files-found: error
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          tag_name: ${{ steps.vars.outputs.short_sha }}
          files: bazel-bin/java/com/google/copybara/copybara_deploy.jar
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
